services:
  db:
    image: mysql:8.4.0
    restart: always
    container_name: dosomedev-db
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: dosomedev
      MYSQL_USER: dbusr
      MYSQL_PASSWORD: dbpwd
    volumes: 
      - /srv/dosomedev/db/mysql_8.4.0:/var/lib/mysql:rw
