FROM node:22.9.0-bookworm

RUN apt-get update
RUN apt-get install nginx -y

COPY tmp/view/dosomedev-view/dist /var/www/html
COPY nginx.conf /etc/nginx/sites-available/default

EXPOSE 8080

ENTRYPOINT ["nginx", "-g", "daemon off;"]
